// index 首页
export const SETSELECTOR = "SETSELECTOR"
export const GETBANNERS = "GETBANNERS"
export const GETNAVS = "GETNAVS"
export const GETMINIPROGRAMSHARE = "GETMINIPROGRAMSHARE"
export const TRAININGCOUNT = "TRAININGCOUNT"
export const GETMARKETING = "GETMARKETING"
// login 登录获取用户信息
export const GETUSERINFO = "GETUSERINFO"
export const CHANGELOGINSTATE = "CHANGELOGINSTATE"
export const GETLOGINPOPUP = "GETLOGINPOPUP"
export const SETSHOWACTIVITY = "SETSHOWACTIVITY"
export const GETPOPUP = "GETPOPUP"
export const GETGUIDINFO = "GETGUIDINFO"
export const GETINVITEUSERID = "GETINVITEUSERID"
export const GETUSERACCOUNTSTATE = "GETUSERACCOUNTSTATE"
export const GETREDIRECTURL = "GETREDIRECTURL"
// account/benefit 用户权益
export const GETBENEFITINTR = "GETBENEFITINTR"
export const GETBENEFITS = "GETBENEFITS"
// account/collect
export const GETCOLLECTLIST = "GETCOLLECTLIST"
export const CHANGECOLLECTSTATE = "CHANGECOLLECTSTATE"
// account/baseinfo
export const GETCONFIGS = "GETCONFIGS"
export const GETCONTENT = "GETCONTENT"
// acount/storenav
export const GETSTORENAVS = "GETSTORENAVS"
// account/shoppingGuide
export const GETSTORES = "GETSTORES"
// poster 海报
export const GETSHAREINFO = "GETSHAREINFO"
export const GETINVITEQR = "GETINVITEQR"
// CUP 有料
export const GETCUPLIST = "GETCUPLIST"
export const CHANGECOLLECT = "CHANGECOLLECT"
// BRARTS 
export const GETBRARTSLIST= "GETBRARTSLIST"
// 社区活动
export const GETACTIVITYLIST = "GETACTIVITYLIST"
export const GETCURRENTCITY = "GETCURRENTCITY"
export const GETACTIVITYCITIES = "GETACTIVITYCITIES"
// 体态训练营 
export const GETCOURSELIST = "GETCOURSELIST"
export const GETCOURSEDETAIL = "GETCOURSEDETAIL"
export const GETCLASSIFYLIST = "GETCLASSIFYLIST"
export const GETCLASSIFY = "GETCLASSIFY"
export const CHANGECOURSE = "CHANGECOURSE"
export const GETDATELIST = "GETDATELIST"
export const GETALLCATEGORYIES = "GETALLCATEGORYIES"
// 积分
export const CHANGESIGNDATA = "CHANGESIGNDATA"
export const GETSIGNRECORD = "GETSIGNRECORD"
export const GETINTEGRALWAYS = "GETINTEGRALWAYS"
export const GETINTEGRALRECORD = "GETINTEGRALRECORD"
export const CHANGEWAYSTATE = "CHANGEWAYSTATE"